### ISSUE TITLE
compilation error while using react component member as event handler

### ISSUE THREAD

**Issue by sfaerber** [dotnet-websharper/react#5]
First of all, thanks for the great work on WebSharper!
This code leads to error in the while doing the websharper compilation on my machine.

    open WebSharper
    open WebSharper.JavaScript
    open WebSharper.React
    open WebSharper.React.Html

    [<JavaScript>]
    module Client =
    
        type MainComponent() as this =
            inherit React.Component<unit, unit>(())
            member  __.handleClick _ = ()
            override __.Render() = div[on.click this.handleClick][text "Hello, world!"]
        
        [<SPAEntryPoint>]
        let Main() =
            React.Make MainComponent () |> React.Mount (JS.Document.GetElementById "main")

the displayed error is:

`1>FSC: Fehler FS9001: Constructor not found in JavaScript compilation: unit, Candidates: 'T0`
`1>FSC: Fehler FS9001: Chained constructor is an Inline in a not supported form`

here are the packages used to produce the error:

`<package id="WebSharper" version="4.5.3.310" targetFramework="net461" />`
`<package id="WebSharper.FSharp" version="4.5.3.310" targetFramework="net461" />`
`<package id="WebSharper.React" version="4.5.1.131" targetFramework="net461" />`

**Comment by Jand42** [comment]
Thanks for report, this seems to be caused by `as this` and inheriting from a constructor that is defined as a JS inline.
Quick workaround, if you use `this` identifier on the method, this seems to work:

```fsharp
        override this.Render() =
            div [ on.click this.handleClick ] [text "Hello world"]
```

**Comment by Jand42** [comment]
So this is not directly related to React, but a WebSharper bug in this side case: https://github.com/dotnet-websharper/core/issues/1051

**Comment by mrtank** [comment]
Original issue closed
